const productCategory=[
    {
        id:1,
        label:'Airpodes',
        value:'airpodes'
    },
     {
        id:2,
        label:'Camera',
        value:'camera'
    },
     {
        id:3,
        label:'Earphones',
        value:'earphones'
    },
     {
        id:4,
        label:'Mouse',
        value:'mouse'
    },
     {
        id:5,
        label:'Printers',
        value:'printers'
    },
     {
        id:6,
        label:'Processor',
        value:'processor'
    },
     {
        id:7,
        label:'Refridgerator',
        value:'refridgerator'
    },
     {
        id:8,
        label:'Speakers',
        value:'speakers'
    },
     {
        id:9,
        label:'Trimmers',
        value:'trimmers'
    },
     {
        id:10,
        label:'Televisions',
        value:'televisions'
    },
     {
        id:11,
        label:'Watches',
        value:'watches'
    },
     {
        id:12,
        label:'Mobiles',
        value:'mobiles'
    }
]
export default productCategory